### USER REQUESTS
POST http://localhost:5000/user/user HTTP/1.1
Content-Type: application/json

{
    "userType": "user",
    "username": "Navaneeth",
    "password": "12345678",
    "email": "navaneeth@gmail.com"
}

###
POST http://localhost:5000/user/login HTTP/1.1
Content-Type: application/json

{
    "userType": "user",
    "username": "Navaneeth",
    "password": "12345678"
}

### ADMIN REQUESTS
GET http://localhost:5000/admin/test-admin HTTP/1.1

### AUTHOR REQUESTS
POST http://localhost:5000/author/user HTTP/1.1
Content-Type: application/json

{
    "userType": "author",
    "username": "Abhijeet",
    "password": "12345678",
    "email": "abhijeet@gmail.com"
}

###
POST http://localhost:5000/author/login HTTP/1.1
Content-Type: application/json

{
    "userType": "author",
    "username": "Abhijeet",
    "password": "12345678"
}